# Generated by Django 4.1.7 on 2023-04-14 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_no', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('number', models.CharField(max_length=50)),
                ('appointment_date', models.CharField(max_length=30)),
                ('department', models.CharField(max_length=50)),
                ('doctor', models.CharField(max_length=50)),
                ('message', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.CharField(max_length=200)),
                ('doctor', models.CharField(max_length=200)),
                ('medicine', models.CharField(max_length=200)),
                ('dosage', models.CharField(max_length=2000)),
                ('frequency', models.CharField(max_length=2000)),
                ('start_date', models.CharField(max_length=200)),
                ('end_date', models.CharField(max_length=200)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.appointment')),
            ],
        ),
    ]
