# Generated by Django 4.1.7 on 2023-04-17 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_no', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.BigIntegerField()),
                ('appointment_date', models.CharField(max_length=50)),
                ('appointment_time', models.DateField()),
                ('message', models.CharField(max_length=2000)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.department')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.CharField(max_length=200)),
                ('doctor', models.CharField(max_length=200)),
                ('medicine', models.CharField(max_length=200)),
                ('dosage', models.CharField(max_length=2000)),
                ('frequency', models.CharField(max_length=2000)),
                ('start_date', models.CharField(max_length=200)),
                ('end_date', models.CharField(max_length=200)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.appointment')),
            ],
        ),
    ]
