# Generated by Django 4.1.7 on 2023-04-26 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_alter_appointment_appointment_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='id',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='token_no',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
