# Generated by Django 4.1.7 on 2023-03-30 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('qualification', models.CharField(max_length=500)),
                ('password', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=50)),
                ('profile_img', models.ImageField(upload_to='media/')),
            ],
        ),
    ]
