# Generated by Django 4.1.7 on 2023-05-02 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_opentickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='opentickets',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='opentickets',
            name='phone',
            field=models.BigIntegerField(default=0),
        ),
    ]
