# Generated by Django 4.1.7 on 2023-05-02 07:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_opentickets_email_opentickets_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='opentickets',
            name='generatedDate',
            field=models.DateTimeField(default=datetime.date(2023, 5, 2)),
        ),
    ]
